sonar.projectKey=saharhamraoui_PFE-DevSecopsProject
sonar.organization=saharhamraoui
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
