apiVersion: 1

datasources:
  - name: Google Cloud Monitoring
    uid: google-cloud-monitoring
    type: stackdriver
    access: proxy
    isDefault: true
    jsonData:
      # Use the Cloud Run service account (Application Default Credentials)
      authenticationType: gce
      defaultProject: sahar-pfe
    version: 1
    editable: true
