global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape GCP Cloud Run metrics via stackdriver_exporter
  - job_name: cloud_run
    static_configs:
      - targets: ["172.17.0.1:9255"]
    metrics_path: /metrics
    params:
      google.project-id: ["sahar-pfe"]
